#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : R-joineRML
Version  : 0.4.7
Release  : 47
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/joineRML_0.4.7.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/joineRML_0.4.7.tar.gz
Summary  : Joint Modelling of Multivariate Longitudinal Data and
Group    : Development/Tools
License  : GPL-3.0
Requires: R-joineRML-lib = %{version}-%{release}
Requires: R-joineRML-license = %{version}-%{release}
Requires: R-Rcpp
Requires: R-RcppArmadillo
Requires: R-cobs
Requires: R-doParallel
Requires: R-foreach
Requires: R-generics
Requires: R-ggplot2
Requires: R-lme4
Requires: R-mvtnorm
Requires: R-randtoolbox
Requires: R-tibble
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : R-RcppArmadillo-dev
BuildRequires : R-cobs
BuildRequires : R-doParallel
BuildRequires : R-foreach
BuildRequires : R-generics
BuildRequires : R-ggplot2
BuildRequires : R-lme4
BuildRequires : R-mvtnorm
BuildRequires : R-randtoolbox
BuildRequires : R-tibble
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# joineRML <img src="man/figures/hex.png" width = "175" height = "200" align="right" />

%package lib
Summary: lib components for the R-joineRML package.
Group: Libraries
Requires: R-joineRML-license = %{version}-%{release}

%description lib
lib components for the R-joineRML package.


%package license
Summary: license components for the R-joineRML package.
Group: Default

%description license
license components for the R-joineRML package.


%prep
%setup -q -n joineRML
pushd ..
cp -a joineRML buildavx2
popd
pushd ..
cp -a joineRML buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738769384

%install
export SOURCE_DATE_EPOCH=1738769384
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-joineRML
cp %{_builddir}/joineRML/LICENSE %{buildroot}/usr/share/package-licenses/R-joineRML/12d81f50767d4e09aa7877da077ad9d1b915d75b || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/joineRML/CITATION
/usr/lib64/R/library/joineRML/DESCRIPTION
/usr/lib64/R/library/joineRML/INDEX
/usr/lib64/R/library/joineRML/LICENSE
/usr/lib64/R/library/joineRML/Meta/Rd.rds
/usr/lib64/R/library/joineRML/Meta/data.rds
/usr/lib64/R/library/joineRML/Meta/features.rds
/usr/lib64/R/library/joineRML/Meta/hsearch.rds
/usr/lib64/R/library/joineRML/Meta/links.rds
/usr/lib64/R/library/joineRML/Meta/nsInfo.rds
/usr/lib64/R/library/joineRML/Meta/package.rds
/usr/lib64/R/library/joineRML/Meta/vignette.rds
/usr/lib64/R/library/joineRML/NAMESPACE
/usr/lib64/R/library/joineRML/NEWS.md
/usr/lib64/R/library/joineRML/R/joineRML
/usr/lib64/R/library/joineRML/R/joineRML.rdb
/usr/lib64/R/library/joineRML/R/joineRML.rdx
/usr/lib64/R/library/joineRML/data/Rdata.rdb
/usr/lib64/R/library/joineRML/data/Rdata.rds
/usr/lib64/R/library/joineRML/data/Rdata.rdx
/usr/lib64/R/library/joineRML/doc/index.html
/usr/lib64/R/library/joineRML/doc/joineRML-tidy.R
/usr/lib64/R/library/joineRML/doc/joineRML-tidy.Rmd
/usr/lib64/R/library/joineRML/doc/joineRML-tidy.html
/usr/lib64/R/library/joineRML/doc/joineRML.R
/usr/lib64/R/library/joineRML/doc/joineRML.Rmd
/usr/lib64/R/library/joineRML/doc/joineRML.html
/usr/lib64/R/library/joineRML/doc/technical.Rnw
/usr/lib64/R/library/joineRML/doc/technical.pdf
/usr/lib64/R/library/joineRML/help/AnIndex
/usr/lib64/R/library/joineRML/help/aliases.rds
/usr/lib64/R/library/joineRML/help/figures/hex.png
/usr/lib64/R/library/joineRML/help/joineRML.rdb
/usr/lib64/R/library/joineRML/help/joineRML.rdx
/usr/lib64/R/library/joineRML/help/paths.rds
/usr/lib64/R/library/joineRML/html/00Index.html
/usr/lib64/R/library/joineRML/html/R.css
/usr/lib64/R/library/joineRML/tests/testthat.R
/usr/lib64/R/library/joineRML/tests/testthat/Rplots.pdf
/usr/lib64/R/library/joineRML/tests/testthat/test-#59.R
/usr/lib64/R/library/joineRML/tests/testthat/test-ancillary.R
/usr/lib64/R/library/joineRML/tests/testthat/test-boot.R
/usr/lib64/R/library/joineRML/tests/testthat/test-inputs.R
/usr/lib64/R/library/joineRML/tests/testthat/test-models.R
/usr/lib64/R/library/joineRML/tests/testthat/test-tidy.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/joineRML/libs/joineRML.so
/V4/usr/lib64/R/library/joineRML/libs/joineRML.so
/usr/lib64/R/library/joineRML/libs/joineRML.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-joineRML/12d81f50767d4e09aa7877da077ad9d1b915d75b
